#!/usr/bin/env bash

# check for cmd arguments

if [$# -lt 4]
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign variables arguments
path_to_file= $1
ip= $2
username= $3
path_to_ssh_key= $4

# Disable strct host key checking

scp -o "StrictHostKeyChecking = no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Check transfer outcome
if [$? -eq 0]
	echo "Transfer Successful"
else
	echo "Transfer Failed"
fi
