#!/usr/bin/env bash

# check for command arguments

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign variable arguments
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Disable strict host key checking
scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Check transfer outcome
if [ $? -eq 0 ]; then
    echo "Transfer Successful"
else
    echo "Transfer Failed"
fi

