#!/usr/bin/env bash
# Commands to install nginx on web server.

# To check for updates
sudo apt-get update

# To install
sudo apt-get install -y nginx

# To check status
sudo service nginx status

# To display inputs
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t
sudo service nginx reload
