#!/usr/bin/env bash
# Commands to install nginx on web server.

# To check for updates
sudo apt-get update

# To install
sudo apt-get -y install nginx

# To check status
#sudo service nginx status

# To listen to port 80
sudo ufw allow 'Nginx HTTP'

# To display inputs
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t
sudo service nginx reload
