#!/usr/bin/env bash
# This script installs and configure HAProxy on lb-1 server

# install

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*

# configure
sudo vim /etc/haproxy/haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
sudo sed -i "$ a\frontend  web-frontend\n\bind *:80\n\mode http\n\default_backend web-backend\n\backend web-backend\n\balance roundrobin\n\server web-01 34.224.63.7:80 check\n\server web-02 54.157.186.248:80 check
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo systemctl service haproxy start.
