#!/usr/bin/env bash
# this script creates, defines and quits a file.

#Create PID file
echo $$ > /var/run/myscript.pid

# Define signal handler function

function sigterm_handler
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 0
}

function sigint_handler
{
	echo "Y U no love me?!"
}

function sigquit_handler
{
	rm /var/run/myscript.pit
	exit 0
}

# Register signal handlers
trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

# Display message indefinitly

while true 
	do
	echo "To infinty and beyond"
	slee 2
	done
