#!/bin/bash
# this script displays the content of the file as an extention of the 100-read_and_cut task

while IFS=: read -r username password userid groupid userdesc homedir shell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell.
	 User ID's place is protected by the passcode $password, more info about the user here: $userdesc"
done < /etc/passwd

