#!/usr/bin/env bash

# This script displays "Best School" 10 times, but on the 9th iteration,
# it displays "Best School" and then "Hi" on a new line.

i=0
while ((i < 10)); do
    if ((i == 8)); then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i+1))
done

