#!/usr/bin/env bash
#This script is to configure ubuntu server

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

sudo service networking restart

